name: Run ShopHunter Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Enable manual triggering

jobs:
  run-playwright-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      - name: Install Playwright dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install  # Install browser binaries

      - name: Run login_shop_hunter script
        run: python login_shop_hunter.py

      - name: Upload authorization.json
        uses: actions/upload-artifact@v3
        with:
          name: authorization
          path: authorization.json
